### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by vitya0717** [dieterblancke/DonatorJoinPlus#1]
**Describe the bug**
When I leave from my server I got this
https://pastebin.com/2LaiwBQ7

**Versions:**
My server version:
![ver2](https://user-images.githubusercontent.com/50296138/76699296-85000300-66ac-11ea-97af-878d2c62e3ee.PNG)

Latest spigot version
![ver](https://user-images.githubusercontent.com/50296138/76699260-32264b80-66ac-11ea-916c-8cfe0eb44ae4.PNG)

**Comment by dieterblancke** [comment]
Could you please send your config aswell?

Edit: don't forget to hide out any passwords

**Comment by vitya0717** [comment]
https://pastebin.com/UWNAZdTZ

**Comment by dieterblancke** [comment]
I'm assuming it works now? Or didn't you test it yet? You can find the build here: https://github.com/dieterblancke/DonatorJoinPlus/actions/runs/56070242 !
