### ISSUE TITLE
Error 522 Connection timed out

### ISSUE THREAD

**Issue by WhiTe-Yak** [dieterblancke/DonatorJoinPlus#4]
**Describe the bug**
 Error 522 Ray ID: 698842b65cdd15fe • 2021-10-03 18:34:15 UTC
Connection timed out

https://prnt.sc/1unlcww

**Comment by dieterblancke** [comment]
I am aware of this yes, the page should come back tomorrow or Tuesday I hope, in the meantime you can download the latest version from the Actions tab here in GitHub: https://github.com/dieterblancke/DonatorJoinPlus/actions/runs/1291320972
